version: '3.3'

services:
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    command: redis-server --save '' --appendonly no --loglevel warning --protected-mode no
    volumes:
      - squoolr_prod_cache:/data
  mysql:
    image: mysql:latest
    # environment:
    #   - MYSQL_ROOT_PASSWORD=12345678
    #   - MYSQL_DATABASE=squoolr_prod_db
    ports:
      - "5047:3306"
    volumes:
      - squoolr_prod_data:/var/lib/mysql
  api:
    build:
      dockerfile: ./Dockerfile.squoolr-v2.api
      context: .
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:12345678@mysql/squoolr_prod_db
      - REDIS_URL=redis
      - SESSION_SECRET=squoolr-session-secret
      - SESSION_NAME=__sqlrId
      - SESSION_AGE=3600000
      - CRYPTJS_SECRET=I_hate_trash
      - APP_PORT=8000
      - SALT=12
      - ADMIN_URL=https://manager.squoolr.com
      - NX_API_BASE_URL=https://be.squoolr.com
      - NOTCH_API_KEY=sb.uAcDvJnHIxUNecc9Nd3Mka6SggHkLVsZZfHmZNqKbacGeW4GfoI8R6wOyLvQgulWRv8vni1EfWasH8iU5sUFckDPLtb2cZzjW0YIhGUDXmEtv9e3vTyMex2JlLXwF
      - ADMIN_PASSWORD=default-password
      - PLATFORM_FEE=2000
      - ONBOARDING_FEE=50000
      - ADMIN_EMAIL=glomexam@gmail.com
    ports:
      - "86:8000"
    depends_on:
      - mysql
      - redis
  landing:
    build:
      dockerfile: ./Dockerfile.squoolr-v2.landing
      context: .
    restart: always
    ports:
      - "91:3000"
    depends_on:
      - api
  admin:
    build:
      dockerfile: ./Dockerfile.squoolr-v2.admin
      context: .
    restart: always
    ports:
      - "85:3000"
    depends_on:
      - api
volumes:
  squoolr_prod_cache:
    driver: local
  squoolr_prod_data:
    driver: local




# ingl.io, www.ingl.io, lynkr.net {
#         reverse_proxy localhost:83
# }

# beta.ingl.io {
#         reverse_proxy localhost:84
# }

# app.ingl.io {
#         reverse_proxy localhost:89
# }

# marketplace.ingl.io {
#         reverse_proxy localhost:92
# }

# admin.squoolr.com {
#         reverse_proxy localhost:85
# }

# squoolr.com {
#         reverse_proxy localhost:91
# }

# api.squoolr.com {
#         reverse_proxy localhost:86
# }

# student.squoolr.com {
#         reverse_proxy localhost:87
# }

# hopehome.app, www.hopehome.app {
#         reverse_proxy localhost:93
# }

# api.hopehome.app {
#         reverse_proxy localhost:95
# }

# pay.xafshop.com {
#         reverse_proxy localhost:98
# }

# api.xafshop.com {
#         reverse_proxy localhost:99
# }

# accountant.xafshop.com {
#         reverse_proxy localhost:100
# }

# admin.xafshop.com {
#         reverse_proxy localhost:88
# }

# app.xafshop.com {
#         reverse_proxy localhost:101
# }

# api-stage.xafshop.com {
#         reverse_proxy localhost:102
# }

# accountant-stage.xafshop.com {
#         reverse_proxy localhost:103
# }

# admin-stage.xafshop.com {
#         reverse_proxy localhost:104
# }

# app-stage.xafshop.com {
#         reverse_proxy localhost:105
# }

# pay-stage.xafshop.com {
#         reverse_proxy localhost:106
# }

#db.xafshop.com {
#       reverse_proxy localhost:5037
#}