version: '3.3'

services:
  redis_container:
    image: redis:alpine
    ports:
      - 6380:6379
  mysql_container:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=skeleton_db
    command: mysqld --sql_mode=""
  api:
    build:
      dockerfile: ./Dockerfile.api
      context: .
    restart: always
    environment:
      - REDIS_HOST=redis_container
      - REDIS_PORT=6380
      - PRISMA_SECRET=k1.aesgcm256.ztwF1a4stlVgXXJM9lH1ATgN_B-hYEfVcoSmVAFeWGA=
      - DATABASE_URL=mysql://root:12345678@mysql_container:3306/skeleton_db
      - NX_CRYPTJS_SECRET=skeleton-end-to-end-crypting
      - SALT=12
      - SECURE_PHRASE_LENGTH=5
      - SESSION_SECRET=squoolr-session-secret
      - SESSION_NAME=SQUOOLR_SESSION_ID
      - APP_PORT=8080
      - MAX_AGE=600
      - CLIENT_BASE_URL=https://admin.squoolr.com
      - GOOGLE_CLIENT_ID='752561817920-8esi5105gks06dugi9l14h7dg23vdnff.apps.googleusercontent.com'
      - GOOGLE_SECRET='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'
      - EMAIL_HOST='smtp.gmail.com'
      - EMAIL_USER='glomexam@gmail.com'
      - EMAIL_PASSWORD='..........'
      - ADMIN_URL='admin.squoolr.com'
    ports:
      - "83:8080"
    depends_on:
      - mysql_container
      - redis_container
  landing:
    build:
      dockerfile: ./Dockerfile.landing
      context: .
    restart: always
    environment:
      - NX_API_BASE_URL='https://api.squoolr.com'
    ports:
      - "84:3000"
    depends_on:
      - api
  admin:
    build:
      dockerfile: ./Dockerfile.admin
      context: .
    restart: always
    environment:
      - NX_API_BASE_URL='https://api.squoolr.com'
    ports:
      - "85:4200"
    depends_on:
      - api
  personnel:
    build:
      dockerfile: ./Dockerfile.personnel
      context: .
    restart: always
    environment:
      - NX_API_BASE_URL='https://api.squoolr.com'
    ports:
      - "86:4200"
    depends_on:
      - api
  student:
    build:
      dockerfile: ./Dockerfile.student
      context: .
    restart: always
    environment:
      - NX_API_BASE_URL='https://api.squoolr.com'
    ports:
      - "87:4200"
    depends_on:
      - api

