version: '3.3'

services:
  redis_container:
    image: redis:alpine
    ports:
      - 6379:6379
  mysql_container:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=skeleton_db
    command: mysqld --sql_mode=""
  api:
    build:
      dockerfile: ./Dockerfile.api
      context: .
    restart: always
    environment:
      - REDIS_HOST=redis_container
      - REDIS_PORT=redis_container
      - DATABASE_URL=mysql://root:12345678@mysql_container:3306/squoolr_api_db
      - SALT=12
      - SECURE_PHRASE_LENGTH=5
      - SESSION_SECRET=squoolr-session-secret
      - SESSION_NAME=SQUOOLR_SESSION_ID
      - APP_PORT=8080
      - MAX_AGE=600
      - GOOGLE_CLIENT_ID=752561817920-8esi5105gks06dugi9l14h7dg23vdnff.apps.googleusercontent.com
      - GOOGLE_SECRET=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
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_USER=glomexam@gmail.com
      - EMAIL_PASSWORD=..........
      - ADMIN_URL=admin.squoolr.com
      - NODE_ENV=production
      - CRYPTJS_SECRET=I_hate_trash
    ports:
      - "94:8080"
    depends_on:
      - mysql_container
      - redis_container
  landing:
    build:
      dockerfile: ./Dockerfile.landing
      context: .
    restart: always
    ports:
      - "91:3000"
    depends_on:
      - api
  admin:
    build:
      dockerfile: ./Dockerfile.admin
      context: .
    restart: always
    ports:
      - "85:3000"
    depends_on:
      - api
  personnel:
    build:
      dockerfile: ./Dockerfile.personnel
      context: .
    restart: always
    ports:
      - "86:3000"
    depends_on:
      - api
  student:
    build:
      dockerfile: ./Dockerfile.student
      context: .
    restart: always
    ports:
      - "87:3000"
    depends_on:
      - api
