/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    get: operations["AppController_getData"];
  };
  "/platform-settings": {
    get: operations["AppController_getPlatformSettings"];
  };
  "/auth/signin": {
    post: operations["AuthController_signIn"];
  };
  "/auth/reset-password": {
    post: operations["AuthController_resetPassword"];
  };
  "/auth/new-password": {
    post: operations["AuthController_setNewPassword"];
  };
  "/auth/log-out": {
    delete: operations["AuthController_logOut"];
  };
  "/auth/user": {
    get: operations["AuthController_getUser"];
  };
  "/demands/all": {
    get: operations["DemandController_getAllDemands"];
  };
  "/demands/{school_code}": {
    get: operations["DemandController_getDemandStatus"];
  };
  "/demands/{school_code}/details": {
    get: operations["DemandController_getDemandDetails"];
  };
  "/demands/new": {
    post: operations["DemandController_submitDemand"];
  };
  "/demands/validate": {
    put: operations["DemandController_validateDemand"];
  };
  "/demands/{school_code}/status": {
    put: operations["DemandController_updateDemandStatus"];
  };
  "/academic-years/all": {
    get: operations["AcademicYearsController_getAcademicYears"];
  };
  "/academic-years/new": {
    post: operations["AcademicYearsController_createAcademicYear"];
  };
  "/academic-years/{academic_year_id}/choose": {
    patch: operations["AcademicYearsController_chooseActiveAcademicYear"];
  };
  "/inquiries/all": {
    get: operations["InquiriesController_getAllInquiries"];
  };
  "/inquiries/new": {
    post: operations["InquiriesController_createInquiry"];
  };
  "/ambassadors/all": {
    get: operations["AmbassadorsController_getAmbassadors"];
  };
  "/ambassadors/{ambassador_id}": {
    get: operations["AmbassadorsController_getAmbassador"];
  };
  "/ambassadors/{referral_code}/verify": {
    get: operations["AmbassadorsController_getAmbassador"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    PlatformSettingsEntity: {
      platform_settings_id: string;
      onboarding_fee: number;
      /** Format: date-time */
      created_at: string;
    };
    SignInDto: {
      email: string;
      password: string;
    };
    ResetPasswordDto: {
      email: string;
    };
    SetNewPasswordDto: {
      reset_password_id: string;
      new_password: string;
    };
    SchoolEntity: {
      school_name: string;
      school_acronym: string;
      school_email: string;
      lead_funnel: string;
      school_phone_number: string;
      paid_amount: number;
      ambassador_email: string;
      school_code: string;
      /** @enum {string} */
      school_demand_status: "PENDING" | "PROCESSING" | "REJECTED" | "VALIDATED";
      school_rejection_reason: string;
    };
    PersonEntity: {
      first_name: string;
      last_name: string;
      email: string;
      phone_number: string;
      /** Format: date-time */
      birthdate: string;
      /** @enum {string} */
      gender: "Male" | "Female";
      address?: string | null;
      national_id_number: string;
      person_id: string;
      birthplace: string | null;
      nationality: string;
      longitude: number | null;
      latitude: number | null;
      /** @enum {string} */
      preferred_lang: "en" | "fr";
      image_ref: string | null;
      home_region: string | null;
      religion: string | null;
      handicap: string;
      /** @enum {string} */
      civil_status: "Married" | "Single" | "Divorced";
      /** @enum {string|null} */
      employment_status: "Employed" | "Unemployed" | "SelfEmployed" | null;
      /** Format: date-time */
      created_at: string;
    };
    DemandDetails: {
      school: components["schemas"]["SchoolEntity"];
      person: components["schemas"]["PersonEntity"];
    };
    CreatePersonDto: {
      first_name: string;
      last_name: string;
      email: string;
      phone_number: string;
      /** Format: date-time */
      birthdate: string;
      /** @enum {string} */
      gender: "Male" | "Female";
      address?: string;
      national_id_number: string;
      password: string;
    };
    CreateSchoolDto: {
      school_name: string;
      school_acronym: string;
      school_email: string;
      lead_funnel: string;
      referral_code?: string;
      school_phone_number: string;
      /** Format: date-time */
      initial_year_starts_at: string;
      /** Format: date-time */
      initial_year_ends_at: string;
    };
    SubmitDemandDto: {
      payment_phone?: string;
      configurator: components["schemas"]["CreatePersonDto"];
      school: components["schemas"]["CreateSchoolDto"];
    };
    ValidateDemandDto: {
      school_code: string;
      rejection_reason?: string;
      subdomain?: string;
    };
    AcademicYearEntity: {
      /** Format: date-time */
      starts_at: string;
      /** Format: date-time */
      ends_at: string;
      academic_year_id: string;
      year_code: string;
      /** Format: date-time */
      started_at: string;
      /** Format: date-time */
      ended_at: string;
      /** @enum {string} */
      year_status: "INACTIVE" | "ACTIVE" | "FINISHED";
      school_id: string;
      /** Format: date-time */
      created_at: string;
    };
    CreateAcademicYearDto: {
      /** Format: date-time */
      starts_at: string;
      /** Format: date-time */
      ends_at: string;
    };
    ActiveYearSessionData: {
      academic_year_id: string;
      /** Format: date-time */
      starting_date: string;
      /** Format: date-time */
      ending_date: string;
      /** @enum {string} */
      year_status: "INACTIVE" | "ACTIVE" | "FINISHED";
      year_code: string;
    };
    StudentSessionData: {
      annual_student_id: string;
      activeSemesters: string[];
      classroom_code: string;
      classroom_level: number;
      student_id: string;
    };
    ConfiguratorSessionData: {
      annual_configurator_id: string;
      is_sudo: boolean;
    };
    TeacherSessionData: {
      annual_teacher_id: string;
      hourly_rate: number;
      origin_institute: string;
      has_signed_convention: boolean;
      classroomDivisions: string[];
      teacher_id: string;
    };
    DesirializedRoles: {
      login_id: string;
      school_id?: string;
      tutorStudentIds?: string[];
      activeYear: components["schemas"]["ActiveYearSessionData"];
      annualStudent?: components["schemas"]["StudentSessionData"];
      annualConfigurator?: components["schemas"]["ConfiguratorSessionData"];
      annualTeacher?: components["schemas"]["TeacherSessionData"];
      annualRegistry?: components["schemas"]["TeacherSessionData"];
    };
    InquiryEntity: {
      email: string;
      phone?: string;
      name?: string;
      message?: string;
      /** @enum {string} */
      type: "Default" | "EarlyAccess";
      inquiry_id: string;
      /** Format: date-time */
      created_at: string;
    };
    CreateInquiryDto: {
      email: string;
      phone?: string;
      name?: string;
      message?: string;
      /** @enum {string} */
      type: "Default" | "EarlyAccess";
    };
    AmbassadorEntity: {
      ambassador_id: string;
      referral_code: string;
      login_id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AppController_getData: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AppController_getPlatformSettings: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PlatformSettingsEntity"];
        };
      };
    };
  };
  AuthController_signIn: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_resetPassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_setNewPassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetNewPasswordDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_logOut: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_getUser: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DemandController_getAllDemands: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["SchoolEntity"][];
        };
      };
    };
  };
  DemandController_getDemandStatus: {
    parameters: {
      path: {
        school_code: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["SchoolEntity"];
        };
      };
    };
  };
  DemandController_getDemandDetails: {
    parameters: {
      path: {
        school_code: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["DemandDetails"];
        };
      };
    };
  };
  DemandController_submitDemand: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitDemandDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["SchoolEntity"];
        };
      };
    };
  };
  DemandController_validateDemand: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ValidateDemandDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  DemandController_updateDemandStatus: {
    parameters: {
      path: {
        school_code: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  AcademicYearsController_getAcademicYears: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AcademicYearEntity"][];
        };
      };
    };
  };
  AcademicYearsController_createAcademicYear: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAcademicYearDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AcademicYearEntity"];
        };
      };
    };
  };
  AcademicYearsController_chooseActiveAcademicYear: {
    parameters: {
      path: {
        academic_year_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["DesirializedRoles"];
        };
      };
    };
  };
  InquiriesController_getAllInquiries: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["InquiryEntity"][];
        };
      };
    };
  };
  InquiriesController_createInquiry: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateInquiryDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["InquiryEntity"];
        };
      };
    };
  };
  AmbassadorsController_getAmbassadors: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AmbassadorEntity"][];
        };
      };
    };
  };
  AmbassadorsController_getAmbassador: {
    parameters: {
      path: {
        ambassador_id: string;
        referral_code: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AmbassadorEntity"];
        };
      };
    };
  };
}
